CREATE TABLE IF NOT EXISTS "config"(
  "id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  "option" TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS "users"(
  "id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  "login" TEXT UNIQUE NOT NULL,
  "password" TEXT NOT NULL,
  "created" TEXT NOT NULL,
  "is_admin" INTEGER NOT NULL DEFAULT '0'
);
CREATE TABLE IF NOT EXISTS "movies"(
  "id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  "name" TEXT NOT NULL,
  "description" TEXT,
  "released" INTEGER NOT NULL, 
  "price" REAL DEFAULT '10.00', 
  "in_stock" INTEGER DEFAULT '10'
);
CREATE TABLE IF NOT EXISTS "rental"(
  "id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  "movie_id" INTEGER NOT NULL REFERENCES "movies"("id"),
  "user_id" INTEGER NOT NULL REFERENCES "users"("id"),
  "date" TEXT
);
CREATE TABLE IF NOT EXISTS "history"(
  "id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  "user_id" INTEGER NOT NULL,
  "movie_id" INTEGER NOT NULL,
  "action" TEXT NOT NULL,
  "date" TEXT NOT NULL
);